apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: workflow-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ab642bc8e59a311e99f0f06c6421f175-1910322875.us-west-2.elb.amazonaws.com
    http:
      paths:
      - path: /workflows
        backend:
          serviceName: workflow-api
          servicePort: 80